# Generated by Django 5.0 on 2023-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=models.CharField(default='hy', max_length=120),
            preserve_default=False,
        ),
    ]
